### ISSUE TITLE
HTML::FormFu::Preload warns about deprecated Chained traits

### ISSUE THREAD

**Issue by Sadrak** [fireartist/HTML-FormFu#34]
$ perl -MHTML::FormFu::Preload\ 999
Implicit use of the Chained trait is deprecated. Please load MooseX::Attribute::Chained explicitly at /home/felixostmann/perl5lib/lib/Moose/Meta/Attribute/Custom/Trait/Chained.pm line 19.
HTML::FormFu::Preload version 999 required--this is only version 2.01.
BEGIN failed--compilation aborted.

In FormFu 0.09005 this warning also occure and was fixed in 0.09006.

From the Changes:
0.09006 2012-01-23
    - fixed deprecation warnings of MX::Attribute::Chained (bricas)
...

I don't understand what is going on, but i guess there is one missing "use MooseX::Attribute::Chained;" somewhere ...

```
$ for I in $(find HTML/FormFu/ -name "*.pm" | perl -pe 's/\//::/g; s/\.pm//;'); do echo $I; perl -M$I\ 999; done 1>> /tmp/html-formfu.bug 2>&1

$ grep deprecated /tmp/html-formfu.bug -B1
HTML::FormFu::Plugin::RequestToken
Implicit use of the Chained trait is deprecated. Please load MooseX::Attribute::Chained explicitly at /home/felixostmann/perl5lib/lib/Moose/Meta/Attribute/Custom/Trait/Chained.pm line 19.
--
HTML::FormFu::Preload
Implicit use of the Chained trait is deprecated. Please load MooseX::Attribute::Chained explicitly at /home/felixostmann/perl5lib/lib/Moose/Meta/Attribute/Custom/Trait/Chained.pm line 19.
--
HTML::FormFu::Element::RequestToken
Implicit use of the Chained trait is deprecated. Please load MooseX::Attribute::Chained explicitly at /home/felixostmann/perl5lib/lib/Moose/Meta/Attribute/Custom/Trait/Chained.pm line 19.
```

So the RequestToken is the problem, but i don't see why. They load MooseX::Attribute::Chained explicitly like evey other module. After some digging in other Elements i find MooseX::Attribute::FormFuChained! Changing to FormFuChained in HTML::FormFu::Plugin::RequestToken and HTML::FormFu::Element::RequestToken the warning is gone. I will copy now, make the change and then run all the tests and make a pull request.

**Comment by Sadrak** [comment]
OK, running to fast ...

HTML::FormFu::Element::RequestToken is not in HTML::FormFu, it is in Catalyst::Controller::HTML::FormFu!

And there is already a pull-request:
https://github.com/fireartist/Catalyst-Controller-HTML-FormFu/pull/3

So my problem could be fixed with a new version.

You can close this issue when Catalyst::Controller::HTML::FormFu is fixed. Thanks a lot!

**Comment by nigelm** [comment]
Fix applied to  Catalyst::Controller::HTML::FormFu - closing
