### ISSUE TITLE
2.03 tag is missing in git

### ISSUE THREAD

**Issue by karenetheridge** [fireartist/HTML-FormFu#40]
I see you are using `[@Git]` in dist.ini, but somehow when you did the last release, the 2.03 tag never got pushed up to the repository.

Perhaps the release was done from a different repository, and this repo failed to fetch the tags?

**Comment by nigelm** [comment]
Just noticed that and am wondering why - its not in the local repo either....

**Comment by djzort** [comment]
https://github.com/fireartist/HTML-FormFu/tree/v2.03

**Comment by nigelm** [comment]
Had manually pushed a release tag for the last release (2.03) - unfortunately the normally associated release commit was missing.

Have just pushed out 2.05 and that has the tag, but no additional commit... side effects of rearranging the dzil git and change to @Starter confused things.  This should now be fixed
for the next release...
